### ISSUE TITLE
Custom log file not display

### ISSUE THREAD

**Issue by ahmedju** [sevdokimov/log-viewer#104]
Thanks very much for your nice work.

How can I add custom path log file ?

I tried this but my custom log file not shown:

```
        @Bean
	public Map<Path, LogFormat> getLogConfigurations() {
		File f = new File("./info/logs/errors/fileError.log");
		LogbackLogFormat logbackLogFormat = new LogbackLogFormat("%date %level [%thread] [%file:%line] %msg%n");
		
		Map<Path, LogFormat> logs = new HashedMap();
		logs.put(f.toPath(), logbackLogFormat);
		
		return logs;
	}
```

the default spring log its shown my custom log not

**Comment by sevdokimov** [comment]
You defined a bean of type `Map<Path, LogFormat>` , but you have to define a bean of `com.logviewer.logLibs.LogConfigurationLoader`
Example:
```
    @Bean
    public LogConfigurationLoader customConfigLoader() {
        return () -> {
            File f = new File("./info/logs/errors/fileError.log");
            LogbackLogFormat logbackLogFormat = new LogbackLogFormat("%date %level [%thread] [%file:%line] %msg%n");

            Map<Path, LogFormat> logs = new HashedMap();
            logs.put(f.toPath(), logbackLogFormat);

            return logs;
        };
    }
```

**Comment by ahmedju** [comment]
Brother before any thing very very thanks for you for every thing, fast response, nice work and every thing

please I face this error with attachment 
![image](https://user-images.githubusercontent.com/13928485/153356653-32997c76-eeb4-4991-9cdf-8f30abcc4ca4.png)

**Comment by ahmedju** [comment]
and thanks very much for you Sevdokimov

**Comment by ahmedju** [comment]
no need bro I know the issue

I was get the path like this:
File f = new File("./info/logs/errors/fileError.log");

and this path its mean the current folder, and that not found the file correctly "./info/logs/errors/fileError.log" because  when run below:
File f = new File(System.getProperty("./info/logs/errors/fileError.log");
f = new File(f.getAbsolutePath());

and the URL will be:
localhost:9080/logs/log?path=D:\Eclipse\STS\sts-4.11.1.RELEASE\workspaces\Osama\org.eska.billing.report/./info/logs/errors/fileError.log

and this wrong.

the correct to be:
File f = new File(System.getProperty("user.dir") + "/info/logs/errors/fileError.log");
f = new File(f.getAbsolutePath());

**Comment by ahmedju** [comment]
Thanks very very much, you are do a nice work.
