### ISSUE TITLE
Dynamic Logs

### ISSUE THREAD

**Issue by ahmedju** [sevdokimov/log-viewer#107]
Thanks very much for your nice work.

Please how can I use it for dynamic log files for Spring Log Viewer ?

I tried make the bean as prototype not singleton but also not work, its run it only first time and not call it when call /logs 
```
@Bean
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public LogConfigurationLoader customConfigLoader() {
...
}
```

please please is there any way to update the logs dynamically ?, even use Reflection or update it manually, please any way that work, and thanks very much in advance and for your nice work

**Comment by sevdokimov** [comment]
You have to create a spring bean implementing `com.logviewer.api.LvPathResolver`. Each time when you open "http://my-host/logs/?log=all-my-logs" , the system will call `LvPathResolver.resolvePath("all-my-logs")`  to convert "all-my-logs" to a real path / path**s** .

Also, there is `LvFileAccessManagerImpl lvLogManager` bean responsible for permission checking. By default, it allows opening autodetected logs only. You can specify while list of directories or file patterns:
```
        LvFileAccessManagerImpl accessManager = applicationContext.getBean(LvFileAccessManagerImpl.class);

        accessManager.setPaths(Arrays.asList(
                PathPattern.directory(Paths.get("/opt/my-app/logs")),
                PathPattern.fromPattern("/var/log/*.log")
        ));

```

**Comment by ahmedju** [comment]
Thanks very very much, you helped me a lot, thanks very much Sevdokimov
