### ISSUE TITLE
Add button for Search Direction next to Search Bar (needed for mobile use)

### ISSUE THREAD

**Issue by Olivier6767** [sevdokimov/log-viewer#133]
I'm using Logviewer mostly on mobile.
By default it opens the tail of the logfile (most recent entries) which is good.
When typing a search word in the search bar, the search is done forward, meaning it starts from the displayed position (end of file) and searches towards the end of the file.
At this point I get the message:
```
Not Found
Try find to another direction (press Shift-F3 to search back)
```

However on a mobile device it si nto possible to access the Shift and F3 keys...

Would it be possible to add and up and arrow next to the search bar to select the search direction?

**Comment by sevdokimov** [comment]
The "next" and "previous" buttons are to the right of the input field. But the input field is too wide, the buttons are out of screen, but you can scroll it to right.
![Screenshot_2022-08-12-18-05-49-954_com android chrome](https://user-images.githubusercontent.com/669696/184385076-c6a02679-650e-481e-a0d2-a5bf8ccb9622.jpg)

The input field must not bee too wide, it's a bug.

**Comment by Olivier6767** [comment]
Thanks for the tip! I did not see this...

Yes the search field is too wide...
