### ISSUE TITLE
Log files cannot be opened

### ISSUE THREAD

**Issue by Olivier6767** [sevdokimov/log-viewer#137]
I use LogRotate to manage the archival of logfiles. It is dobe by adding a .1, .2, .3 extension to the file name.

![logfilesList](https://user-images.githubusercontent.com/28684355/187405819-8ad848b5-8a92-4832-86fc-5c9d1afaf66b.jpg)

I added this entry in the config file so that the files are listed in log-viewer:

`  {
    path: "/logs/**/\*.log\*"  // Shows files like "*.log.1"
  },

  {
    path: "/logs/**/\*.txt\*"  // Shows files with ".txt.1"
  },`

The files appear in Log-Viewer but when I click on them nothing happens, they do not open, the content is not displayed.

![LogViewver](https://user-images.githubusercontent.com/28684355/187405885-36534ef9-7db1-4936-b009-bec714843175.jpg)

The current logfile, (with extension .log or .txt) opens fine.

Am I missing something?

**Comment by sevdokimov** [comment]
The File browser doesn't use that configuration to detect the file type. It detects file type by the hardcoded pattern. "*.log.txt.3" doesn't match that pattern. There is no way to fix the file browser, but the files are available by the direct link: `http://localhost:8333/log?path=/logs/node/webgrabplus/WebGrab++.log.txt.1`

It's not convenient to copypaste the path to URL, you can create a shortcut to open all `WebGrab++.log.txt*` files on one page.
Add the following configuration:
```
log-paths {
    WebGrab = {
        file = "/logs/node/webgrabplus/WebGrab++.log.txt*"
    }
}
```

And all WebGrab logs will be available on `http://localhost:8333/log?path=WebGrab` URL

**Comment by Olivier6767** [comment]
Ok, thanks for the tip.
