### ISSUE TITLE
Не корректная отработка формата времени

### ISSUE THREAD

**Issue by denis-demyanov** [sevdokimov/log-viewer#14]
Приветствую!
v0.1.5
При формате даты с точностью секунды более трех знаков после запятой "зависает" при попытке пролистывании страницы.
Формат:
logs = [
  {
    path: "**/*.log" 
    format: {
      type: LogbackLogFormat
      pattern: "%date{yyyy-MM-dd HH:mm:ss.SSSS} %msg"
    }
  }

![lgw](https://user-images.githubusercontent.com/9023736/105771283-6081e200-5f71-11eb-9625-fa47dc9af1be.JPG)

[example.log](https://github.com/sevdokimov/log-viewer/files/5869917/example.log)

**Comment by sevdokimov** [comment]
Fixed in 0.1.7
