### ISSUE TITLE
Building zip

### ISSUE THREAD

**Issue by ghost** [sevdokimov/log-viewer#154]
How do you build the zip, clean install gives

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign (sign-artifacts) on project log-parent: Execution sign-artifacts of goal org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign failed.: NullPointerException -> [Help 1]

Package does nothing.

**Comment by sevdokimov** [comment]
Maven tries to sign jar (all jar in the Maven Central Repositories must be sign)
You can disable it, just disable "sign" profile: `mvn -P !sign clean install`

**Comment by cuthbe** [comment]
Thanks, another quick one I want to introduce some extra security features. Do I create a branch of 1.0.3?

**Comment by sevdokimov** [comment]
yes, or you can create a pull request to master

**Comment by cuthbe** [comment]
So when I run package the root shows not zip

**Comment by cuthbe** [comment]
I just see
staff   96 Jan  3 18:58 javadoc-bundle-options

**Comment by cuthbe** [comment]
Any thoughts on why this is not building?

**Comment by sevdokimov** [comment]
`package` works fine on my machine, zip appears in log-viewer-cli/target/log-viewer-1.0.4-SNAPSHOT.zip 
Do you see any error message?
