### ISSUE TITLE
Shows disconnected after a while

### ISSUE THREAD

**Issue by sjtuross** [sevdokimov/log-viewer#163]
If I don't interact with the tool for just a while like 1 minute, it shows disconnected as below. Any idea how to prevent it?

![image](https://user-images.githubusercontent.com/940110/220078744-4593499d-ad32-4b84-abbc-6e58225c72b7.png)

**Comment by holograph** [comment]
Ha, I was literally on my way to log this issue 😆 

Adding a bit of info:
- In my case, using latest Firefox stable;
- Nothing logged on the console;
- The web socket "response" tab in inspector shows the usual flurry of activity, and then eventually (with no obvious leading event): `Connection Closed: 1006`

**Comment by holograph** [comment]
A bit more:

```
      1006 is a reserved value and MUST NOT be set as a status code in a
      Close control frame by an endpoint.  It is designated for use in
      applications expecting a status code to indicate that the
      connection was closed abnormally, e.g., without sending or
      receiving a Close control frame.
```

This tells me either the client or the server simply dropped the TCP connection. The server logs show:
```
│ 2023-02-20_10:21:29.619 [qtp1494346128-7824] INFO  c.logviewer.web.LogViewerWebsocket - Connection opened: 60 <anonymous>                                                      │
│ 2023-02-20_10:24:09.973 [qtp1494346128-7745] ERROR c.logviewer.web.LogViewerWebsocket - Connection closed (CloseReason[1006,Disconnected]) 60 <anonymous>
```

**Comment by holograph** [comment]
A quick tcpdump didn't help, but there does not appear any way to reconnect beyond reloading the page. Perhaps (if we can't figure out the cause here) add a reconnect mechanism?

**Comment by ShadowVoyd** [comment]
Just in case you or anyone else might be using this through nginx as a reverse proxy and are experiencing this issue, you need to specify a timeout for that location block that proxies it. 
```
proxy_connect_timeout 1d;
proxy_send_timeout 1d;
proxy_read_timeout 1d;
```

p.s. 
I recommend not exposing this software through a reverse proxy to the internet unless you have it behind some sort of security hardened authentication (authelia is a good working example).

**Comment by sjtuross** [comment]
Thank you for the tips. I indeed have nginx as a reverse proxy. The issue disappears with the suggested proxy timeout options.

**Comment by holograph** [comment]
This affects virtually anyone behind an L7 (probably L4 as well) proxy, so I think this issue isn't really closed. IMO we can:
1. Add a simple "ping every second" mechanism via the websocket (I'll try to take a stab at it)
2. Add recommended settings when behind a load balancer, including a more sensible timeout (say 15 minutes).
@sevdokimov what do you think?

**Comment by ShadowVoyd** [comment]
> This affects virtually anyone behind an L7 (probably L4 as well) proxy, so I think this issue isn't really closed. IMO we can:
> 
> 1. Add a simple "ping every second" mechanism via the websocket (I'll try to take a stab at it)
> 2. Add recommended settings when behind a load balancer, including a more sensible timeout (say 15 minutes).
>    @sevdokimov what do you think?

Websocket only operates at OSI layer 7. If you are using a load balancer like kubernetes and nginx, have you tried setting the times out in the ingress nginx controller?
https://loft.sh/blog/kubernetes-nginx-ingress-10-useful-configuration-options/#timeout-settings

**Comment by sgohl** [comment]
I'm not sure I should open a new issue because this already exists, even if it's closed I just want to add that I'd prefer the disconnected notification not rendering the complete app useless. Only a page refresh would reinitiate the connection.
I'm not too worried about the websocket connection is closed, I more dislike the fact that you can not use the app anymore unless you refresh.
What about a persistent notification at the bottom of the page but still being able to click things?
