### ISSUE TITLE
Feature request: Enable anchor links for specific line numbers/offsets

### ISSUE THREAD

**Issue by holograph** [sevdokimov/log-viewer#164]
Since events are already considered discrete (i.e. right-click + "show event"), perhaps it's easy to enable linking to specific lines, line ranges or offsets? Something like "http://<...>/mylogfile.log#L57-60", similar to GitHub?

**Comment by sevdokimov** [comment]
You can select a line then click Menu -> "Permanent Link to the current position". When somebody opens this link, he will see exactly the same view including selected line, filters, etc..
I'll add the same action to the context menu.

**Comment by holograph** [comment]
That's a stateful thing though, I was thinking something usable for bootstrapping the viewer's initial state (e.g. instead of start at line=<end>-100, start at line 47. Or with byte offset, if that's what's available).

**Comment by holograph** [comment]
... especially since there's no guarantee the log viewer itself will have any access to writable persistent storage, as is the case in my K8s-based setup.

**Comment by sevdokimov** [comment]
Make sense

**Comment by eniantooleeva** [comment]
Strongly need that feature. I have app that builds graph from log and want to give user ability to navigate to log line that is affiliated with certain node. I wanted to do that by inserting link to runing log-viewer server with line number into node property. I am very upset that cannot make that.

**Comment by sevdokimov** [comment]
Fixed in 1.0.8

**Comment by sevdokimov** [comment]
When you select a log record, a suffix like `#p12345` will be added to the URL. `12345` is the offset of the selected line in the log. If more than one log file is opened on the page, the suffix will be `#1a2b3c4d-p12345`, where `1a2b3c4d` is ID of the log file, `12345` is the offset of the selected line.

https://github.com/sevdokimov/log-viewer/assets/669696/32b1e674-d598-4e4d-8619-5f585eded974
