### ISSUE TITLE
files *log.bck can't be opened

### ISSUE THREAD

**Issue by diurczak** [sevdokimov/log-viewer#168]
Hello,
if find out that if i add as pattern:
{
path: "/log//.bck"
}

files can be displayed via web, but they can't be opened.
![image](https://user-images.githubusercontent.com/40499323/225627759-ddde1697-013c-4781-9641-13714b8b3894.png)

i have already tried to apply formats, but wasn't able to see any difference
i have tried as well to rename the file from file.log.bck to file.log, obviously without changing it content, and i was able to open it from web view

anybody can help?

**Comment by sevdokimov** [comment]
Fixed. 
`*.log.bck` will be detected as a log files. Also I added `log-viewer.navigation.log-file-pattern` configuration property to specify a custom log files pattern.
