### ISSUE TITLE
Does not detect format when asci color codes are in logs

### ISSUE THREAD

**Issue by DineshSolanki** [sevdokimov/log-viewer#170]
Thanks for making such a useful and great tool first, I wanted to report the following issue -
it doesn't properly format the logs when log file contains asci color codes such as -
```
22-03-2023 06:17:49.800 [35m[http-nio-9100-exec-8][0;39m [34mINFO [0;39m 
```

its an slf4j log

**Comment by sevdokimov** [comment]
Fixed. 
`%date{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %5level %logger{36} - %msg%n` format will be detected automatically, ascii color codes will be removed automatically.
