### ISSUE TITLE
Autscrolling or Option to enable autoscrolling

### ISSUE THREAD

**Issue by Leviathan09** [sevdokimov/log-viewer#171]
Hi @sevdokimov it would be nice if you could add some feature like autoscrolling as it is when using something like "tail -f" on the log

**Comment by sevdokimov** [comment]
Autoscroll is implemented in v1.0.6.
The page will be scrolled to the end if a user is viewing the end of a log and log grows. Autoscroll is not working when a line is selected, assume a user is focused on the line.
