### ISSUE TITLE
Provide new release

### ISSUE THREAD

**Issue by Leviathan09** [sevdokimov/log-viewer#176]
Hi @sevdokimov 
is it possible to provide a new release with the commits you've done since version 1.0.4
Because i have no idea how to put together the files in your repo to working .jar

**Comment by sevdokimov** [comment]
Does `mvn package -Dmaven.test.skip=true` command help? If you run `mvn package -Dmaven.test.skip=true` in the root of the project, the release will be in `log-viewer/log-viewer-cli/target/log-viewer-1.0.5-SNAPSHOT.tar.gz`.

I'm going to make a release on weekend, after implementation of several features.

**Comment by Leviathan09** [comment]
Hi, i've never used maven before so i took me a while to try it but i get some error messages

```
[[ERROR] Failed to execute goal on project log-viewer-cli: Could not resolve dependencies for project io.github.sevdokimov.logviewer:log-viewer-cli:jar:1.0.5-SNAPSHOT: Could not find artifact io.github.sevdokimov.logviewer:log-viewer:jar:tests:1.0.5-SNAPSHOT
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :log-viewer

```

But i will wait then till the new release

**Comment by sevdokimov** [comment]
Done. 1.0.5 release has been published.
