### ISSUE TITLE
ssh configuration

### ISSUE THREAD

**Issue by sm4tlm** [sevdokimov/log-viewer#191]
Hey, nice one app
but how can I configure application to remote logs via ssh?
thx a lot

**Comment by sevdokimov** [comment]
You cannot load logs from a remote machine via SSH, but you can run a log-viewer instance on a remote machines and connect to it.
For example: let's assume you have `remove-machine-01` and `remote-machine-02` , you can start log-viewer instances on them. In this case, log-viewer UI will be available on `remove-machine-01:8111` and `remove-machine-02:8111`.  You can open logs from both machine on the same page using an URL like `http://localhost:8111/log?log=path-to-my-logs.log@remove-machine-01&log=path-to-my-logs.log@remove-machine-02`
In this case, the log-viewer instance from localhost will connect to the log-viewer instances on `remove-machine-01` and `remove-machine-02` and load data from them. 
Note a log-viewer instance uses 9595 port to provide data for other log-viewers, not 8111 port. So the local log-viewer will connect to `remove-machine-01:9595` and `remove-machine-02:9595`

**Comment by sm4tlm** [comment]
ok, thanks a lot!)
