### ISSUE TITLE
Adding additional file extensions

### ISSUE THREAD

**Issue by veridian69** [sevdokimov/log-viewer#193]
Is it possible to make new filetypes readable by log-viewer? I have some logs written by a third party application and they have a specific name format: USER_date_IP.tracesql I would like to read these files as text. The type is recognised by log-viewer as unknown, which is fine, but the double click, open logfile functionality doesn't work as there is no associated viewer for this type.

**Comment by sevdokimov** [comment]
You can use `log-viewer.navigation.log-file-pattern` configuration property to specify a custom log extentions. The value of the property is a regexp to match file path. Example (config.conf):
```
log-viewer.navigation.log-file-pattern=".+\\.tracesql"
```

**Comment by veridian69** [comment]
perfect - that's the one. thanks!
