### ISSUE TITLE
jdk 21

### ISSUE THREAD

**Issue by cberni** [sevdokimov/log-viewer#205]
Hello!

Do you have any plans to make it compatible with JDK 21?

**Comment by cberni** [comment]
any up?

**Comment by sevdokimov** [comment]
@cberni What is wrong with JDK 21? I tried JDK 21, no problems.

**Comment by cberni** [comment]
Sorry, I just tested it, and it seems to be working fine now.
Initially, my classmate had mentioned it wasn't compatible, and I believed them.
