### ISSUE TITLE
SpringBoot configuration

### ISSUE THREAD

**Issue by bevrard** [sevdokimov/log-viewer#56]
Trying to use the springboot configuration:
I've added your configuration file to the scan:
![image](https://user-images.githubusercontent.com/8151690/120190076-6423bf00-c218-11eb-9b97-07eefc91b2f7.png)

I get this error:
```
2021-05-31 13:53:38.022 ERROR 12408 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [org.wallride.bootstrap.Bootstrap]; nested exception is java.io.FileNotFoundException: class path resource [com/logviewer/springboot/LogViewerSpringBootConfig.class] cannot be opened because it does not exist

```

![image](https://user-images.githubusercontent.com/8151690/120190387-d2688180-c218-11eb-8ac4-07b534e3acee.png)

If I simply copy your configuration file in a local file:
![image](https://user-images.githubusercontent.com/8151690/120190883-7c480e00-c219-11eb-826c-94e833be4274.png)
It doesn't found your autoconfiguration or servlet from your library.

Am I missing something?

Thanks in advance

**Comment by sevdokimov** [comment]
The missing classes are located in `com.logviewer:log-viewer:0.1.6` jar. `com.logviewer:log-viewer-spring-boot:0.1.6` has dependency to it. 
Does `com.logviewer:log-viewer:0.1.6` jar come as a transitive dependency?

**Comment by bevrard** [comment]
I needed to add the dependency in another module (as it was a multimodule project).  It works now 🙂.
