### ISSUE TITLE
download log file

### ISSUE THREAD

**Issue by cberni** [sevdokimov/log-viewer#63]
Is there a option to download the file log?
would be very interesting to download de full log file sometimes... and also if the file is already compressed (.gz, .zip)...

**Comment by sevdokimov** [comment]
Good idea. Will implement it in the future.

**Comment by ar3thien** [comment]
+1

**Comment by sevdokimov** [comment]
Log downloading is supported in 1.0.1 , there is "Download" item in the menu.
