### ISSUE TITLE
context path in config file

### ISSUE THREAD

**Issue by cberni** [sevdokimov/log-viewer#65]
a great and useful improvement would be a property in config file to set the context path. look the picture below.

![Image 2021-06-08 at 14 57 40](https://user-images.githubusercontent.com/4624597/121245748-c3b44700-c876-11eb-813f-695d11df87d6.jpeg)

**Comment by sevdokimov** [comment]
Fixed in 0.1.7.
`log-viewer.server.context-path` configuration property has been added.
