### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by hitnrun30** [sevdokimov/log-viewer#66]
I can not get shortcuts to be recognized.

I have this value in log-paths

DropIt = {
	file = "C:/HTPC/DropIt/LogFile.log"
}

But it doesn't find the file.

**Comment by sevdokimov** [comment]
The config file contains
```
log-paths = {
    DropIt = {
        file = "C:/HTPC/DropIt/LogFile.log"
    }
}
```

and you open http://localhost:8111/log?path=DropIt , correct?

**Comment by hitnrun30** [comment]
Yes, exactly. Also can you use wood cats with it?

**Comment by sevdokimov** [comment]
Wildcards are supported in 1.0.1, you can specify something like
```
log-paths = {
    DropIt = {
        file = "C:/HTPC/DropIt/*.log"
    }
}
```
