### ISSUE TITLE
Reverse proxy with nginx

### ISSUE THREAD

**Issue by sumitrathore42** [sevdokimov/log-viewer#68]
Hi,
I am trying to deploy this utility at cloud behind nginx server.
I am not able to set its homepage.
Like https://somehost/logs/
so that Js and css could load with the relative path, not with the root.

**Comment by sevdokimov** [comment]
LogViewer works in https://somehost:8111/ , and nginx map it to https://somehost/logs , correct?
You can try to run log-viewer on https://somehost:8111/ using `log-viewer.server.context-path="/logs"` variable. (supported since 0.1.7)

Does nginx passes the original URL to log-viewer somehow?

**Comment by sumitrathore42** [comment]
yes, this works perfect with the IP:PORT
I tried by setting context-path as you suggested.
but when we put it behind nginx, the js and css file are getting 404.
the url currently generated:
https://somehost/styles.c169595171167aaa32f0.css
It should be 
https://somehost/logs/styles.c169595171167aaa32f0.css

nginx configuration is as below.
   
 location /logs {
        include /etc/nginx/includes/proxy.conf;
        proxy_pass http://someip:8111/logs;

**Comment by sevdokimov** [comment]
Got it.
Please, try this https://github.com/sevdokimov/log-viewer/releases/tag/0.1.8-SNAPSHOT release, the problem must be fixed.

**Comment by sumitrathore42** [comment]
@sevdokimov  this worked. Thanks for the quick support.

**Comment by SlodeSoft** [comment]
My config Nginx : 

location /logs {
 root /usr/share/nginx/html/log-viewer-1.0.3/;
 proxy_pass http://127.0.0.1:8111;
}
