### ISSUE TITLE
Unusable on mobile devices - cannot scroll

### ISSUE THREAD

**Issue by Olivier6767** [sevdokimov/log-viewer#74]
Is there a way to make this work on mobile devices?
I tried using safari, chrome and edge on iPhone and iPad and there is no way to scroll.
We can just see the content of the screen but swiping up or down does not scroll the content.

It would be great if this could be fixed, otherwise it cannot be used on mobile devices.

**Comment by sevdokimov** [comment]
Fixed in 1.0.1
