### ISSUE TITLE
"C:\opt\logs" is not accessible due to LogViewer configuration

### ISSUE THREAD

**Issue by JHoerbst** [sevdokimov/log-viewer#78]
Embedded Spring Boot
0.1.8

properties:
log-viewer.default-directory=C:\\opt\\logs\\ 

![image](https://user-images.githubusercontent.com/14820570/127638627-91b73b95-4032-4c66-899a-808bbf019af5.png)

What does this error message mean and how can i fix it?

**Comment by sevdokimov** [comment]
Are you able to open that folder without `log-viewer.default-directory=C:\opt\logs\` property?

**Comment by JHoerbst** [comment]
Without the property it's just an empty page:
![image](https://user-images.githubusercontent.com/14820570/127643034-3e2c12aa-17f2-4448-8f18-923322115043.png)

**Comment by sevdokimov** [comment]
What do you have in `logs = []` section of the configuration?

**Comment by JHoerbst** [comment]
i dont use the config.conf file, i just added the Spring config classes you provided:

`@Import({LogViewerSpringBootConfig.class, LogViewerWebsocketConfig.class})
@SpringBootApplication
public class KoenaMgmtApplication {

    public static void main(String[] args) {
        SpringApplication.run(KoenaMgmtApplication.class, args);
    }

}`

**Comment by sevdokimov** [comment]
Got it.
By default, LogViewer provides access to the application's log only. It doesn't allow viewing any file.
If `c:/opt/logs` contains a fixed number of logs, you can add them to log-viewer. To do that, you have to define a bean of type `com.logviewer.logLibs.LogConfigurationLoader`.
FYI LogViewer uses `com.logviewer.api.LvFileAccessManager` bean to check whether a file is accessible or not. You can override that bean and implement any logic.

**Comment by JHoerbst** [comment]
Thank you very much, this worked!
