### ISSUE TITLE
Add colors for different levels

### ISSUE THREAD

**Issue by SXI-XLayer** [sevdokimov/log-viewer#85]
I am using the following config:

```
format = {
  type: RegexLogFormat
  regex: "(?<date>\\d\\d:\\d\\d:\\d\\d\\.\\d{3}) - +(?<level>[A-Z]+)\\s+- (?<msg>.+)"
  fields: [
    { name: "date", type: "date" },
    { name: "level", type: "level/log4j" },
    { name: "msg", type: "message" },
  ]
}
```

I see that the ERROR level is highlighted in red, and INFO is in green, however I would like my DEBUG to be in another color (one that I choose - is this possible?

Also how could I get the entire message highlighted in red and the text in white for ERROR messages?

Thanks for a very promising product I will be watching this closely.

**Comment by SXI-XLayer** [comment]
I have also tried the following config and get the same results as with the regex:

format = {
  type: Log4jLogFormat
  pattern: "%date{HH:mm:ss.SSS} - %-5level - %msg%n"
}

**Comment by SXI-XLayer** [comment]
So I then tried the following:

format = {
  type: Log4jLogFormat
  pattern: "%highlight{%date{HH:mm:ss.SSS} - %-5level - %msg%n}{FATAL=white, ERROR=red, WARN=blue, INFO=black, DEBUG=green, TRACE=blue}"
}

But obviously that FAILED spectacularly ...

**Comment by sevdokimov** [comment]
The color scheme for "level" field is defined in https://github.com/sevdokimov/log-viewer/blob/master/log-viewer/src/main/resources/log-viewer-ui.conf
You can override the color for DEBUG by adding the following line to "config.conf"
```
ui-config {
  field-types.level.args.DEBUG.color = "#6ff"
}
```

**Comment by SXI-XLayer** [comment]
Ahhh you are a LEGEND ... thank you..
