### ISSUE TITLE
index.html not found

### ISSUE THREAD

**Issue by nathangary** [sevdokimov/log-viewer#88]
hello,
springboot logs 
index.html not found

**Comment by sevdokimov** [comment]
Hello.
The error comes from LogViewerServlet.processIndexHtml() (line 301). That code loads HTML code from `/log-viewer-web/index.html` resource using `getClass().getResource("/log-viewer-web/index.html")`.
"/log-viewer-web/index.html" resource is located in "log-viewer-frontend-1.0.1.jar". 
Could you make sure that "log-viewer-frontend-1.0.1.jar" is present in the classpath? If yes, check why it is not accessible from LogViewerServlet.
Also, you can attach a project sample to reproduce the problem.

**Comment by nathangary** [comment]
thanks.
resolved
